### ISSUE TITLE
Stamp Does Not Align with Cursor Location

### ISSUE THREAD

**Issue by AndrewLyon** [SynapseWeb/PyReconstruct#35] opened 2024-09-07 00:02 UTC
### Describe the bug

When placing a stamp, the stamp does not align with the location of the cursor

### Commit or version

1.11.0 or 93edd9b

### To Reproduce

place a stamp on image
stamp is significantly below the location that was clicked

### Expected behavior

stamp should align with cursor location

### Desktop environment:

Windows 10

### Python version

3.11.9

### Error messages

None

### Additional context

Fresh/new conda environment, pyreconstruct installed via pip install git+(git website)
While stamp location doesn't align with cursor, tracing does

**Comment by quasiTriestino** [comment] 2024-09-07 15:44
I'm able to place stamps correctly in the field on my end. I see you're on Windows 10. Are you using a mouse or a stylus? And are there any Window updates pending? We have encountered issues like this in the past that were resolved with updating the OS, though the fact you're able to trace but not stamp properly is odd.

A few possibilities:

If you right click on the palette item you can set a stamp radius. If you're making a large stamp and are zoomed in too far, the stamp might appear off if you can only see a part of it. Also, If you click and drag while making a stamp, the stamp diameter will be based off of that distance and not the radius set in the palette. (For example, clicking and dragging across the width of a circular structure will make a stamp with that structure's diameter.) This also might be an issue, if you're accidentally dragging.

Could you post a screenshot of with a structure first traced and then stamped?

**Comment by AndrewLyon** [comment] 2024-09-17 02:03
The system is loosely controlled by my universities IT. That being said, it is on the most current update of Windows 10 (22H2, the september version) and the most current nvidia graphics driver.
Issues remain with a new environment and are not present on a pc with windows 11 on the same data set.
Images attached were generated by tracing with a tracing pad, though the same issue occurs when the mouse is used. The traces and the stamps are of the same thing, though in the stamped image, the stamps are about 2.2 units lower on the Y axis than where they are supposed to be placed.
![trace](https://github.com/user-attachments/assets/66731439-c3b5-4cc3-bdf7-045759decae3)
![stamp](https://github.com/user-attachments/assets/4e5c8bf2-1544-4b9d-b9a4-056d449266dc)

**Comment by quasiTriestino** [comment] 2024-09-17 12:49
If you think the offset of the stamps is a fixed value, we could apply the reverse of that every time you click. This is a hacky solution to the problem, but if you're able to trace and stamp ok outside of your IT environment, then I assume this is where the problem is.

When you click to place a stamp in your IT environment, the stamp appears misplaced, correct? By that I mean, stamps placed correctly on another machine don't appear misplaced when you open the series on your IT machine?

**Comment by AndrewLyon** [comment] 2024-09-18 01:33
After experimenting with another data set on the same PC, it appears to be an issue with just the data set.

**Comment by quasiTriestino** [comment] 2024-09-18 18:16
No problems with the new dataset?

**Comment by AndrewLyon** [comment] 2024-09-20 06:25
Oddly enough, no. The issue appears to be with the file itself.
I have opened the .jser on my Mac and the issue is still present.

The file originates from the windows xp version of reconstruct. For some reason the same data set fails to convert into the new version of pyreconstruct on its original PC, but converted successfully on this windows 10 pc.

I have the .jser, would you be interested in it by chance?

**Comment by quasiTriestino** [comment] 2024-09-20 09:57
I would! You can send it to m.chirillo@utexas.edu

**Comment by quasiTriestino** [comment] 2024-10-17 14:09
Given this is an issue specific to a single jser file, I am closing this issue. Please re-open it if you note problems with other series. Thanks!

**Closed by quasiTriestino** 2024-10-17 14:09 UTC
Labels: bug
